/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Characters_Sharky.gltf -o src/components/Sharky.jsx -r public 
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { useControls } from "leva";

export function Sharky(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/Characters_Sharky.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  console.log(actions)

  const { animation } = useControls({
    animation: { value: "Idle", options: Object.keys(actions) },
  });

  useEffect(() => {
    actions[animation].reset().fadeIn(0.5).play();
    return () => {
      actions[animation].fadeOut(0.5);
    }
  },[animation])

  return (
    <group ref={group} {...props} dispose={null} castShadow>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <skinnedMesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.Atlas} skeleton={nodes.Cube001.skeleton} />
          <skinnedMesh name="Sharky" geometry={nodes.Sharky.geometry} material={materials.Atlas} skeleton={nodes.Sharky.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Characters_Sharky.gltf')
